import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Footer from "../components/Footer/Footer";
import Link from "next/link";


const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>REST API & NEXT JS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="xl:mx-96">
        <Image src="/resources/programming.webp" width={1000} height={500} className="w-full h-[500px]"></Image>
        <div className="bg-gray-900 py-28 flex justify-center gap-4">
          <Link href="/" className="btn">Home</Link>
          <Link href="/posts" className="btn btn-primary">Posts</Link>
          <Link href="/users" className="btn btn-accent">Users</Link>
        </div>
        <Footer/>
      </main>
    </>
  );
}
